name: Test Docker
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  Normal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check default.sh
      run: shellcheck scripts/default.sh

    - name: Build Image
      run: docker build --tag emcniece/dockeryourxyzzy .

    - name: Inspect
      run: docker inspect emcniece/dockeryourxyzzy

  Prebuilt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build Image
      run: make built-image

    - name: Inspect
      run: built-inspect