name: Docker

on:
  push:
    branches:
      - '**'
    tags:
      - "v*"
    paths:
      - .github/workflows/docker.yml
      - "docker-bake.hcl"
      - "Dockerfile"

jobs:

  Docker:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          imageType: ["prebuilt", "on-demand"]
      steps:

      - name: Login to Docker
        uses: docker/login-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          username: cyb3rjak3
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login To GitHub
        uses: docker/login-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: cyb3rjak3/dockeryourxyzzy,ghcr.io/cyb3r-jak3/dockeryourxyzzy
          labels: |
            org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/DockerYourXyzzy.git
            org.label-schema.schema-version=1.0.0-rc1
            maintainer=Cyb3r Jak3 jake@jwhite.network
            org.opencontainers.image.vendor=cyb3rjak3

      - name: Build
        uses: docker/bake-action@v3
        with:
          files: |
            ${{ steps.meta.outputs.bake-file }}
            ./docker-bake.hcl
          targets: ${{matrix.imageType}}-release
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          set: |
            *.cache-from=type=gha,scope=buildx-${{matrix.imageType}}
            *.cache-to=type=gha,mode=max,scope=buildx-${{matrix.imageType}}
        env:
          DOCKER_META_VERSION: ${{ steps.meta.outputs.version }}
